### ISSUE TITLE
Add token-based security for some API calls

### ISSUE THREAD

**Issue by ryoe** [nerdbeers/nerdbeers#39]
This could be useful for certain types of maintenance tasks to run on demand:

- db vacuum
- clear the visitor log
- etc.

**Comment by datachomp** [comment]
It would.

**Comment by ryoe** [comment]
So this is done? :stuck_out_tongue_winking_eye:

**Comment by ryoe** [comment]
Oh, I see this is done via this commit: https://github.com/nerdbeers/nerdbeers/commit/75618530f9ee7e794e2de7a6a30a35b8799b1f27
