### ISSUE TITLE
Navigation on Mobile

### ISSUE THREAD

**Issue by datachomp** [nerdbeers/nerdbeers#56]
The navigation....oh....the navigation.

**Comment by darrencauthon** [comment]
There's this scene in Jurassic Park where Nedry hits a sign with his vehicle. He needs to know where the sign told him to go, so he gets out and picks the sign up. But the sign is busted and there's no way to know where it was pointing, so he spins it in frustration. 

If I could have found an animated gif of this scene, I'd post it here. It would fit.

**Comment by datachomp** [comment]
This inside joke has run its course. Closing because I've filled my laugh quota.

**Comment by darrencauthon** [comment]
I actually watched this part of Jurassic Park since then.

Not work making the meme gif... the turning sign image, the picture I had stuck in my mind... was pretty small, and in the bottom-right corner of the screen.  I don't think it would make a good meme.
