### ISSUE TITLE
Jurassic Park Ned .gifs

### ISSUE THREAD

**Issue by datachomp** [nerdbeers/nerdbeers#58]
This issue is related to closed issue #56 .  While that issue was originally around the navigation oh the navigation  joke, it went tangential to Jurassic Park stuff.  Rather than leave 56 open with mixed intent, I am leaving it closed and leaving this issue open for the Jurassic Park stuff.   Once we feel we have satisfied that need, we can close this issue.   Thanks everyone for surfacing this and hopefully we can get it resolved in a manner that keeps all parties happy.

**Comment by datachomp** [comment]
http://i1.ytimg.com/vi/aPUTf3_ZpVA/0.jpg

**Comment by darrencauthon** [comment]
:smile:
