### ISSUE TITLE
Site under too much load - fix proposed

### ISSUE THREAD

**Issue by datachomp** [nerdbeers/nerdbeers#62]
Given the amount of load both the site and the DB experience during events, I've come up with a sure-fire fix. Since Ruby 2.3 is expected to have performance gains,  I propose we just bump the site to  2.3.0-preview1.  This seems far more safer/easier than trying to mess with upgrading flimsy hardware or unstable vm's (hacker news links about this).   I was planning on doing this 30 minutes before the next event as that also seems like the easiest way to test that it works.

**Comment by datachomp** [comment]
+1

**Comment by darrencauthon** [comment]
As usual, @datachomp is ignoring the big picture.

Updating to Ruby 2.3 is fine, but why not upgrade to Rails 5.0?  I heard it also has big performance updates -- and its new features can be used to make the site even more performant.

New features like... Active-Somethin's, I can't remember their names, but they are fast.  And with each major update of Rails we get the benefits of more **thought leadership** to fix the things we've been doing in 4 that are **all wrong**.

**Comment by darrencauthon** [comment]
BTW what is a "VM"?  Are they like dynos?  Because you could always just increase the dyno dial to get more performance.

**Comment by datachomp** [comment]
@darrencauthon , to get Rails 5, do I just need to update the ActiveRecords gem?

**Comment by datachomp** [comment]
The VM stands for 'Visual Manager' it is what majority of "startups" (think of startups as like a business without an actual business model)  use to manage their apps. Sometimes you add new VM's... sometimes you remove them based on what level of Amazon Prime you have.

**Comment by darrencauthon** [comment]
Need more web performance? It's never been easier.

Just make sure you bump your Heroku database from "dev" to "hobbist" to support the extra connections.

![images duckduckgo-2](https://cloud.githubusercontent.com/assets/148768/11402459/aa7da262-935d-11e5-88af-96e9f02a67ed.jpg)

**Comment by darrencauthon** [comment]
@datachomp Ah, I'm not sure how to update to Rails 5, I'm waiting for someone to write a script to run a bunch of arbitrary commands on my web app.

**Comment by jbavari** [comment]
I'm on windows and I'm trying to install linux with ruby 2.3 on top of it how do i do it please respond need help asap please respond +1

**Comment by datachomp** [comment]
@darrencauthon is that like some sort of Arduino app?

**Comment by datachomp** [comment]
@jbavari wow, moron.   It's a rails app not a linux.  Please read the other pull requests before looking so dumb. -1

**Comment by darrencauthon** [comment]
@datachomp No that's my new UI for increasing my Heroku dynos.  I WROTE IT IN REACT!

**Comment by darrencauthon** [comment]
@jbavari You'll need more +1's than that if you want us to answer your question!

**Comment by datachomp** [comment]
@jbavari you should be addressing these problems in the dedicated ICQ channel.  Github isn't the place to discuss poorly thought out changes to the code basecamp before an event.

**Comment by jbavari** [comment]
@datachomp please fix. I'm running Javascript on Rails and Im trying to compile ICQ like you said. Please fix.

**Comment by datachomp** [comment]
@ryoe can you please email @jbavari our  Otto file with the correct linux and ruby so he can get to the ICQ area for his issue?  thanks.    +1

**Comment by jbavari** [comment]
@ryoe I have node installed and im trying run npm and it doesnt ICQ. Can we please PR it? Please fix.

**Comment by jbavari** [comment]
@ryoe This issue is top priority my company needs this fixed please fix. I look forward to hearing from @datachomp

**Comment by datachomp** [comment]
@jbavari wait, are you using this on your companies intranet or extranet?

**Comment by snellingio** [comment]
so whats the deployment strategy? custom docker file? heroku has the same support for the 2.3 preview as @jbavari's windows machine

**Comment by datachomp** [comment]
@snellingio yes, that is what is proposed.   +1?

**Comment by datachomp** [comment]
@snellingio It is a linux-rails app, not a heroku.

**Comment by tracehelms** [comment]
@datachomp I'm trying to use the linux rails app to print MapQuest directions to my sister's house for Thanksgiving, but it's not working. Worst app ever. Please add printer support ASAP. Need it by tomorrow morning.

**Comment by snellingio** [comment]
@datachomp is that different than gnu/linux?

**Comment by datachomp** [comment]
@tracehelps please PR that fix. We don't have an official peering agreement with MapQuests at this time. We mostly do KingsQuest and other gems like that.  If you can get the license in place and a PR a review team will respond to your work appropriately.

**Comment by datachomp** [comment]
@snellingio I have no idea if this is gnu/linux. I'm not an academic. I know that per the spec, this is a rails-linux app.

**Comment by darrencauthon** [comment]
Can I get a strong-named version of this fix?

**Comment by datachomp** [comment]
@darrencauthon the repo is called  nerdbeers/nerdbeers for exactly that reason.

**Comment by datachomp** [comment]
jbavari I don't think taht fixed it.  Can you please test your PR's before I have to merge them?

**Comment by jbavari** [comment]
@ryoe @datachomp How to test runs?

**Comment by jbavari** [comment]
@ryoe @datachomp @tracehelms @jeff-french 

http://stackoverflow.com/questions/30446426/installing-ruby-in-linux

https://gorails.com/setup/ubuntu/14.04

@datachomp @ryoe

**Comment by datachomp** [comment]
This has been fixed with microservice, multi-cloud-native-architecture first principles approach, and    a new javascript framework.

**Comment by darrencauthon** [comment]
Can this new version scale?

**Comment by datachomp** [comment]
hello @darrencauthon, first let me say welcome to to this repo.   2nd, based on your non-hyphenated use of the world `scale` I can only assume you are new to technology.   It is common courtesy in modern programming issues to attach what level of scale you are talking about when asking about basic architecture patterns.

for example: 'can this web-scale?'    'can this planet-scale?'   'can this unicorn-scale?'   'can this fish-scale?'   'can this hockey-stick-scale?'

With the above learnings in mind, please rephrase your question.
